FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY prisma ./prisma
RUN npx prisma generate
COPY src ./src
RUN mkdir -p /uploads
EXPOSE 3100
CMD ["sh", "-c", "npx prisma db push --accept-data-loss && node src/index.js"]
